### ISSUE TITLE
TPM error when activating credential

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#168]
```
keylime_agent_1      | WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:321:Esys_ActivateCredential_Finish() Received TPM Error 
keylime_agent_1      | ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x00000101) 
keylime_agent_1      | Error: TPM(Tss2Error(FormatZero(FormatZeroResponseCode { .0: 257, error_number: 1, format_selector: false, version: true, tcg_vendor_indicator: false, severity: false })))

```

**Comment by puiterwijk** [comment]
We hit that in the normal Keylime as well. It's the "commands no longer accepted due to a failure" error code that means the activate call failed due to cryptographic failure.
It's caused  by the EK cert being wrong, which is caused by passing `--allow-signing` to `swtpm_setup`.
So you will want to re-create your swtpm setup, and *not* pass that flag in.

Alternatively, use a hardware TPM.

**Comment by lkatalin** [comment]
Thanks a lot for this explanation, @puiterwijk !! I've submitted a PR to fix this in the `docker-compose` setup.
