### ISSUE TITLE
"drop-in" infrastructure

### ISSUE THREAD

**Issue by frozencemetery** [keylime/rust-keylime#25]
Eventually we're going to want to test our cloud node in a full environment.  The easiest ways to do this are probably either modify the MIT installer (or ours, if we have one by that point) to set it up, or install a new cloud node that's ours into an existing keylime environment.

**Comment by lukehinds** [comment]
Would an ansible playbook be useful here, or do you prefer to keep the decencies to a minimum (and not rely on the ansible client and its python dependencies (just thinking of the other issue you have raised about an offline installer))? 

I have a playbook [0] for setting up the IBM emulator which I could reuse parts of , alongside some new playbooks to deploy keylime MIT. We could then have ansible (with a Vagrantfile) bring up one VM (or container) for running MIT KL and another VM running the cloud node. 

We could easily kick off some functional tests around the full architecture and it could be something to use in CI in time? Or a way for those interested in contributing, be enabled to bootstrap an env quickly to allow them to look around and try KL out.

I could find some time to work on this as a side project. I understand though if the preference is to keep installation offline and with the least amount of dependencies (bash being everywhere, unlike ansible). 

[0] https://github.com/lukehinds/ansible-tpm-simulator

**Comment by frozencemetery** [comment]
I'm not against ansible for installing a whole keylime environment, I think.  (Since right now the rest is all python, it even makes sense.)  While ansible induces some additional dependencies, I believe they're only on the machine running ansible, not on the machines ansible configures, so that's not a big issue.

I don't know whether it's an actual prerequisite, but the situation you're describing sounds nice :)

**Comment by lukehinds** [comment]
@frozencemetery , I will start working on something!

**Comment by lukehinds** [comment]
I have a ansible role available now:

https://github.com/lukehinds/ansible-keylime

https://galaxy.ansible.com/lukehinds/ansible_keylime/ansible_keylime

It deploys both python-keylime / ibm emu and rust keylime cloud node, but does not set up the rust client as default the default cloud node (this requires a port change in /etc/keylime.conf), but I figure the rust client is not ready yet.

I am sure if can be improved over time, where we can perhaps add some ansible vars for building using certain git tags / branches and setting params such as ports or setting up cfssl.

If you like this I have no strong opinion on where we keep it. If we want we can host it here on or my personal repo. I think the main thing is it needs to be in it's own repo, so that galaxy.ansible.com can pull down the latest.

**Comment by frozencemetery** [comment]
This is great, thanks @lukehinds!  I think keeping it in its own repo for now makes sense.
