### ISSUE TITLE
Handle incoming POST requests

### ISSUE THREAD

**Issue by mbestavros** [keylime/rust-keylime#65]
Per the Keylime spec, the Rust agent needs to be able to handle incoming POST requests, including dealing with new U/V keys and payloads. This issue will serve to track progress on building that functionality in.

**Comment by leonjia0112** [comment]
Here is the discussion during the meeting about the persistent key import and export topic.

@mbestavros 11:07
Making progress. I talked offline with Robbie and Leo last week about it; major blocker at this point is that we don't persist RSA keys across sessions, making it hard to test. (We currently generate them randomly upon starting the Keylime node.) So right now I'm working on getting RSA key import/export working
We also had a brief discussion about how best to persist keys across sessions; we figure that for now we'll just do it like Python and write keys to a file, though we will probably note that it would be worthwhile to investigate in a more secure way to store keys

@lukehinds 11:09
what would constitute a 'session'?

@jetwhiz 11:10
for keylime we're storing in a securityfs mount at /var/lib/keylime

@lukehinds 11:11
secure_mount is in the rust client as well
main thing is to keep them away from /tmp.

@mbestavros 11:11
As in, every time we run cargo test, the RSA key is regenerated (making it hard to test decrypting a payload)

@jetwhiz 11:12
are these the keys that protect U and V, or the bootstrap key itself?

@lukehinds 11:12
I see, makes sense now. So for tests can we not keep dummy keys that are copied into place?

@mbestavros 11:14
For testing (and even development), probably -- but for any of this to actually work, key import/export has to be there

@jetwhiz 11:15
keylime python allowed importing of the bootstrap key (optional)
but the RSA keys that protect the U,V key pairs are random (they don't need to be persisted)
the bootstrap key doesn't need to be persistent, though

@lukehinds 11:18
does that help @mbestavros ?
or should we flesh this out more in a GH isssue?
/s/a/the

@mbestavros 11:19
My understanding, from reading the Python code, was that upon bootup, the node would check if there was a key already generated and import it. If it wasn't there, it would generate one. That's what I'm trying to replicate here

@atothRedHat 11:20
understanding check, bootstrap key is for CA creation?

@mbestavros 11:20
My understanding is that we needed that key to do most of the work of handling a POST request

@jetwhiz 11:20
the bootstrap key is sort of like a DH key, it is randomly generated to transfer a secure payload to a node (which could include a CA cert payload)
oh do you mean the verifier's HTTPS certs?

**Comment by jetwhiz** [comment]
@mbestavros which RSA keys are being talked about here specifically?  Are these the ones protecting the U,V keypair halves (which are always randomly generated in python Keylime), or the ones used for the REST interface (or some other RSA keys)?  

Note that the Keylime agent only communicates over HTTP and does not need HTTPS keys for REST communication.

**Comment by mbestavros** [comment]
@jetwhiz: The code starting [here](https://github.com/keylime/keylime/blob/47651e28e53b4d8a6157d50ad7343c6679956260/keylime/cloud_agent.py#L360) is what I was referring to. I'm assuming those are the REST interface keys.

My understanding from reading that code was that the key needed to be persisted on disk; it seems as though the `rsa_key` variable initialized there is used later on. Happy to be corrected if this isn't the case.

**Comment by leonjia0112** [comment]
There are so many keys around here. \(0,0)/ 
I think @mbestavros means the `rsa_keyname = tci_rsa_key` which is later stored in the `/var/lib/keylime/secure/` which is owned by root. So he is suggesting to find a better solution for the key storage if I understand this right.

**Comment by jetwhiz** [comment]
@mbestavros @leonjia0112 

Yes that's the randomly-generated, temporary RSA keypair that is used to protect the `U`,`V` key shares over the wire (recall that `U` and `V` are two halves of the secret bootstrap key `Kb` that we're trying to provision the agent with).  They are not stored to disk, though, since `/var/lib/keylime/secure/` is a securityfs filesystem that exists only in memory.  That means that the keys are wiped out every time the node is restarted, and there is no need to store them long-term.  

That RSA keypair is only needed temporarily during the bootstrapping process and could be thrown away after the secret bootstrap key, `Kb`, is derived.  If you look at the ACSAC presentation (https://github.com/keylime/keylime/blob/master/doc/llsrc-keylime-acsac-v6.pptx), this is the `NK` key discussed on slide 16 ("Keylime Bootstrap Key Derivation Details (Part 1)").  

This `NK` keypair is necessary since all of the communications that the agent takes part in are over unencrypted HTTP (since we have no secrets yet, we have no way of doing encrypted comms).  We do not want an eavesdropper to steal the `U`,`V` key halves while they are in transit to the agent, since then they will have our secret bootstrap key, `Kb`. 

The general workflow is: 
1. Tenant wants to send secret bootstrap key, `Kb`, to agent X
2. Split `Kb` into two halves => `U` and `V` (where `V` is sent to the verifier by the tenant)
3. Agent X sends their public `NK` RSA key to tenant and verifier (randomly created)
4. Verifier and tenant encrypt `V` and `U` with public `NK` (so only agent X can decrypt it)
5. Agent X receives encrypted `V` and `U` halves, decrypts them and recombines to obtain `Kb`

Take a look over slides 16 and 17 and let me know if you have any questions, but hopefully this is more clear.

**Comment by nabilschear** [comment]
@jetwhiz has it all right.  The main reason we stored it was for continence and speed...and honestly for debugging and development.  It just took a while to generate the key and I didn't want to wait for it =)

**Comment by mbestavros** [comment]
@jetwhiz, thanks for this -- was super helpful, and it makes a lot more sense now. I see what you meant when you said it was like a DH key.

If we don't absolutely need key import (and it seems like we don't), then I'll refocus on building out POST handling with random keys, as we have now.

**Comment by jetwhiz** [comment]
@mbestavros no problem!  

And just to clarify, the REST calls involving the agent are all unencrypted (over standard HTTP), so the POST calls themselves don't use any keys (no HTTPS/TLS).  The encryption discussed above is happening within Keylime and sent as an encrypted blob over HTTP REST calls.  

For instance, see here where the verifier encrypts its `V` key half with the agent's random public `NK` RSA key and stores it in a JSON object to send: https://github.com/keylime/keylime/blob/master/keylime/cloud_verifier_common.py#L256

````python
def prepare_v(agent):
    # be very careful printing K, U, or V as they leak in logs stored on unprotected disks
    if common.INSECURE_DEBUG:
        logger.debug("b64_V (non encrypted): " + agent['v'])
        
    if agent.get('b64_encrypted_V',"") !="":
        b64_encrypted_V = agent['b64_encrypted_V']
        logger.debug("Re-using cached encrypted V")
    else:
        # encrypt V with the public key
        b64_encrypted_V = base64.b64encode(crypto.rsa_encrypt(crypto.rsa_import_pubkey(agent['public_key']),str(base64.b64decode(agent['v']))))
        agent['b64_encrypted_V'] = b64_encrypted_V
        
    logger.debug("b64_encrypted_V:" + b64_encrypted_V)
    post_data = {
              'encrypted_key': b64_encrypted_V
            }
    v_json_message = json.dumps(post_data)
    return v_json_message
````

It then sends the JSON object (with encrypted `V`) to the agent over standard HTTP REST: https://github.com/keylime/keylime/blob/master/keylime/cloud_verifier_tornado.py#L342

````python
v_json_message = cloud_verifier_common.prepare_v(agent)
agent['operational_state'] = cloud_verifier_common.CloudAgent_Operational_State.PROVIDE_V
client = tornado.httpclient.AsyncHTTPClient()
url = "http://%s:%d/keys/vkey"%(agent['ip'],agent['port'])
cb = functools.partial(self.on_provide_v_response, agent, url)
client.fetch(url, method="POST", callback=cb, headers=None, body=v_json_message)
````

**Comment by lukehinds** [comment]
How is this progressing @mbestavros ?
