### ISSUE TITLE
IAK creation 

### ISSUE THREAD

**Issue by kabakaev** [keylime/rust-keylime#888]
Hello! May I ask, why you decided to [create an IAK for tests with `tpm_createprimary`](https://github.com/keylime/rust-keylime/blob/2a91d664b99cf6c42ef766d61c9da43af12c19ff/tests/generate-iak-idevid-certs.sh#L224) instead of [`tpm2_createak`](https://github.com/tpm2-software/tpm2-tools/blob/5.7/man/tpm2_createak.1.md)?

I see that `tpm2_createak` does not attach the authorization policy hash. Is it the reason, or is there something else flawed in the tpm2_createak implementation?

**Comment by ansasaki** [comment]
The reason is that we need to add the unique data defined in Table 7.3.1 of the [specification](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf)

Please join the `#keylime` channel in [CNCF slack instance](https://slack.cncf.io/) to ask this kind of question instead of creating issues.
